baseURL: "https://chutommy.github.io/rand/"
enableInlineShortcodes: true
languageCode: "en-us"
title: "Go package chutommy/rand"
theme: "uwe-uwe"
relativeURLs: true

disableKinds:
  - "section"
  - "taxonomy"
  - "term"
  - "RSS"

markup:
  goldmark:
    renderer:
      unsafe: true
    highlight:
      style: igor

params:

  uweuwe:
    metadata:
      author: "Tommy Chu"

    logo:
      display: true
      src: "/assets/img/logo/logo.png"

    favicon:
      display: true
      src: "/assets/img/logo/favicon.png"

    shortDesc:
      display: true
      value: "Clean and easy to use math/rand library clone with a true random generator."

    platformLinks:
      display: true
      displayMode: "as-icons-and-text"

      platforms:
        - name: "author"
          display: true
          iconSrc: "/assets/img/platforms/personal.png"
          target: "https://chutommy.github.io/"
          text: "Author"
          title: "Go to author's website"

        - name: "source"
          display: true
          iconSrc: "/assets/img/platforms/github.png"
          target: "https://github.com/chutommy/rand"
          text: "Source"
          title: "Go to the Observer Github repository"

        - name: "documentation"
          display: true
          iconSrc: "/assets/img/platforms/document.png"
          target: "https://pkg.go.dev/github.com/chutommy/rand"
          text: "Documentation"
          title: "Go to the package documentation page"

    toc:
      display: true

    googleAnalytics:
      active: true
      id: G-KJLLCGTNQQ

    renderHooks:
      image:
        use: true

      link:
        use: true

      heading:
        use: true

    syntaxHiglighingCustom:
      use: false