/*
Package rand provides a true random generator.
The numbers are generated by a source, which is provided
by a function from the crypto/rand. Since
the crypto/rand package has really weak and unfriendly interface,
this package combines its capability of generating true random numbers
with the method set which is provided in the math/rand package.
*/
package rand

import (
	"math/rand"
)

// NewRand generates a new rand.Rand from the math/rand
// with a dynamic source.
//
// Rand implements all functions from the package math/rand package.
// All the math's pseudo-random generators are now true-RNG.
// Keep in mind, that some original methods,
// such as Seed(), does not work anymore.
//
// See: https://pkg.go.dev/math/rand?tab=doc#Rand
func NewRand() *rand.Rand {
	return rand.New(NewSource())
}
