// Package rand provides a true random generator.
//
// The numbers are generated by a source, which is provided
// by a function from the crypto/rand. And since
// the crypto/rand package has really weak and unfriendly interface,
// this package combines its capability of generating true random numbers
// with the functions which are provided in the math/rand,
// the generator of pseudo-random numbers.
//
// To achieve the true randomness, this package uses the Read function
// from the crypto/rand, which by default uses a system's getrandom(2)
// or /dev/urandom functions on Linux/FreeBSD, getentropy(2) on OpenBSD
// and /dev/urandom on other Unix-systems. On Windows it uses
// the CryptGenRandom API and on Wasm the Web Crypto API.
package rand

import (
	rand "math/rand"
)

// Rand is a controller of the true random number generator (TRND).
//
// The original math/rand functions can be obtained with the Rand.Mrand,
// although it is not recommended, since the Rand is identical
// to math's rand.Rand, but only without no-op methods such as Seed()
type Rand struct {
	Mrand *rand.Rand
}

// New generates a new Rand with the source of the RNG.
func New() *Rand {
	return &Rand{
		Mrand: rand.New(newSource()),
	}
}

// Float32 returns a random float32 in range [0;1).
func (r *Rand) Float32() float32 {
	return r.Mrand.Float32()
}

// Float64 returns a random float64 in range [0;1).
func (r *Rand) Float64() float64 {
	return r.Mrand.Float64()
}

// Int returns a non-negative random int.
func (r *Rand) Int() int {
	return r.Mrand.Int()
}

// Int31 returns, as an int32, a non-negative random 31-bit integer.
func (r *Rand) Int31() int32 {
	return r.Mrand.Int31()
}

// Int31n returns, as an int32, a non-negative random 31-bit integer in range [0,n).It panics if n <= 0.
func (r *Rand) Int31n(n int32) int32 {
	return r.Mrand.Int31n(n)
}

// Int63 returns, as an int63, a non-negative random 63-bit integer.
func (r *Rand) Int63() int64 {
	return r.Mrand.Int63()
}

// Int63n returns, as an int64, a non-negative random 63-bit integer in range [0,n).It panics if n <= 0.
func (r *Rand) Int63n() int64 {
	return r.Mrand.Int63()
}

// Intn returns, as an int, a non-negative random number in range [0,n).It panics if n <= 0.
func (r *Rand) Intn(n int) int {
	return r.Mrand.Intn(n)
}

// Perm returns, as a slice of n ints, a random permutation of the integers in range [0,n).
func (r *Rand) Perm(n int) []int {
	return r.Mrand.Perm(n)
}

// Read writes len(p) random bytes into p. It returns len(p) and a nil error. Read should not be called concurrently with any other Rand method.
func (r *Rand) Read(p []byte) (int, error) {
	return r.Mrand.Read(p)
}

// Shuffle randomizes the order of elements. n is the number of elements. Shuffle panics if n < 0. swap swaps the elements with indexes i and j.
func (r *Rand) Shuffle(n int, swap func(i, j int)) {
	r.Mrand.Shuffle(n, swap)
}

// Uint32 returns, as an uint32, a -random 32-bit integer.
func (r *Rand) Uint32() uint32 {
	return r.Mrand.Uint32()
}

// Uint64 returns, as an uint64, a -random 64-bit integer.
func (r *Rand) Uint64() uint64 {
	return r.Mrand.Uint64()
}

/*
 * Top-level convenience functions
 */

// Float32 returns a random float32 in range [0;1).
func Float32() float32 {
	r := New()
	return r.Mrand.Float32()
}

// Float64 returns a random float64 in range [0;1).
func Float64() float64 {
	r := New()
	return r.Mrand.Float64()
}

// Int returns a non-negative random int.
func Int() int {
	r := New()
	return r.Mrand.Int()
}

// Int31 returns, as an int32, a non-negative random 31-bit integer.
func Int31() int32 {
	r := New()
	return r.Mrand.Int31()
}

// Int31n returns, as an int32, a non-negative random 31-bit integer in range [0,n). It panics if n <= 0.
func Int31n(n int32) int32 {
	r := New()
	return r.Mrand.Int31n(n)
}

// Int63 returns, as an int63, a non-negative random 63-bit integer.
func Int63() int64 {
	r := New()
	return r.Mrand.Int63()
}

// Int63n returns, as an int64, a non-negative random 63-bit integer in range [0,n). It panics if n <= 0.
func Int63n() int64 {
	r := New()
	return r.Mrand.Int63()
}

// Intn returns, as an int, a non-negative random number in range [0,n). It panics if n <= 0.
func Intn(n int) int {
	r := New()
	return r.Mrand.Intn(n)
}

// Perm returns, as a slice of n ints, a random permutation of the integers in range [0,n).
func Perm(n int) []int {
	r := New()
	return r.Mrand.Perm(n)
}

// Read writes len(p) random bytes into p. It returns len(p) and a nil error.
func Read(p []byte) (int, error) {
	r := New()
	return r.Mrand.Read(p)
}

// Shuffle randomizes the order of elements. n is the number of elements. Shuffle panics if n < 0. swap swaps the elements with indexes i and j.
func Shuffle(n int, swap func(i, j int)) {
	r := New()
	r.Mrand.Shuffle(n, swap)
}

// Uint32 returns, as an uint32, a random 32-bit integer.
func Uint32() uint32 {
	r := New()
	return r.Mrand.Uint32()
}

// Uint64 returns, as an uint64, a random 64-bit integer.
func Uint64() uint64 {
	r := New()
	return r.Mrand.Uint64()
}
